version: '3.9'

services:
  userapplication:
    container_name: nishantdocker21.userapplication
    image: userapplication:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://userapp_db:5432/userdb
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - userapp_db
  userapp_db:
    container_name: userapp_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: userdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
